# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

section_subjects = SectionSubject.create ([
{subject_id: 157, section_id: 22},
{subject_id: 55, section_id: 112},
{subject_id: 53, section_id: 1},
{subject_id: 55, section_id: 81},
{subject_id: 180, section_id: 141},
{subject_id: 180, section_id: 142},
{subject_id: 180, section_id: 143},
{subject_id: 180, section_id: 144}

	])

departments = Department.create ([

{name: "AC", desc: "Accountancy"},
{name: "EC", desc: "Economics and Public Policy"},
{name: "BE", desc: "Entrepreneurship"},
{name: "FM", desc: "Financial Management"},
{name: "HR", desc: "Human Resource"},
{name: "IT", desc: "Information and Communication Technology"},
{name: "LM", desc: "Legal Management"},
{name: "MC", desc: "Marketing and Corporate Communication"},
{name: "OM", desc: "Operations Management"},
{name: "PS", desc: "Psychology"}

	])

sections = Section.create ([

{name: "A", department_id: 1, yearlevel: "1"},
{name: "B", department_id: 1, yearlevel: "1"},
{name: "C", department_id: 1, yearlevel: "1"},
{name: "D", department_id: 1, yearlevel: "1"},
{name: "A", department_id: 2, yearlevel: "1"},
{name: "B", department_id: 2, yearlevel: "1"},
{name: "C", department_id: 2, yearlevel: "1"},
{name: "D", department_id: 2, yearlevel: "1"},
{name: "A", department_id: 3, yearlevel: "1"},
{name: "B", department_id: 3, yearlevel: "1"},
{name: "C", department_id: 3, yearlevel: "1"},
{name: "D", department_id: 3, yearlevel: "1"},
{name: "A", department_id: 4, yearlevel: "1"},
{name: "B", department_id: 4, yearlevel: "1"},
{name: "C", department_id: 4, yearlevel: "1"},
{name: "D", department_id: 4, yearlevel: "1"},
{name: "A", department_id: 5, yearlevel: "1"},
{name: "B", department_id: 5, yearlevel: "1"},
{name: "C", department_id: 5, yearlevel: "1"},
{name: "D", department_id: 5, yearlevel: "1"},
{name: "A", department_id: 6, yearlevel: "1"},
{name: "B", department_id: 6, yearlevel: "1"},
{name: "C", department_id: 6, yearlevel: "1"},
{name: "D", department_id: 6, yearlevel: "1"},
{name: "A", department_id: 7, yearlevel: "1"},
{name: "B", department_id: 7, yearlevel: "1"},
{name: "C", department_id: 7, yearlevel: "1"},
{name: "D", department_id: 7, yearlevel: "1"},
{name: "A", department_id: 8, yearlevel: "1"},
{name: "B", department_id: 8, yearlevel: "1"},
{name: "C", department_id: 8, yearlevel: "1"},
{name: "D", department_id: 8, yearlevel: "1"},
{name: "A", department_id: 9, yearlevel: "1"},
{name: "B", department_id: 9, yearlevel: "1"},
{name: "C", department_id: 9, yearlevel: "1"},
{name: "D", department_id: 9, yearlevel: "1"},
{name: "A", department_id: 10, yearlevel: "1"},
{name: "B", department_id: 10, yearlevel: "1"},
{name: "C", department_id: 10, yearlevel: "1"},
{name: "D", department_id: 10, yearlevel: "1"},
{name: "A", department_id: 1, yearlevel: "2"},
{name: "B", department_id: 1, yearlevel: "2"},
{name: "C", department_id: 1, yearlevel: "2"},
{name: "D", department_id: 1, yearlevel: "2"},
{name: "A", department_id: 2, yearlevel: "2"},
{name: "B", department_id: 2, yearlevel: "2"},
{name: "C", department_id: 2, yearlevel: "2"},
{name: "D", department_id: 2, yearlevel: "2"},
{name: "A", department_id: 3, yearlevel: "2"},
{name: "B", department_id: 3, yearlevel: "2"},
{name: "C", department_id: 3, yearlevel: "2"},
{name: "D", department_id: 3, yearlevel: "2"},
{name: "A", department_id: 4, yearlevel: "2"},
{name: "B", department_id: 4, yearlevel: "2"},
{name: "C", department_id: 4, yearlevel: "2"},
{name: "D", department_id: 4, yearlevel: "2"},
{name: "A", department_id: 5, yearlevel: "2"},
{name: "B", department_id: 5, yearlevel: "2"},
{name: "C", department_id: 5, yearlevel: "2"},
{name: "D", department_id: 5, yearlevel: "2"},
{name: "A", department_id: 6, yearlevel: "2"},
{name: "B", department_id: 6, yearlevel: "2"},
{name: "C", department_id: 6, yearlevel: "2"},
{name: "D", department_id: 6, yearlevel: "2"},
{name: "A", department_id: 7, yearlevel: "2"},
{name: "B", department_id: 7, yearlevel: "2"},
{name: "C", department_id: 7, yearlevel: "2"},
{name: "D", department_id: 7, yearlevel: "2"},
{name: "A", department_id: 8, yearlevel: "2"},
{name: "B", department_id: 8, yearlevel: "2"},
{name: "C", department_id: 8, yearlevel: "2"},
{name: "D", department_id: 8, yearlevel: "2"},
{name: "A", department_id: 9, yearlevel: "2"},
{name: "B", department_id: 9, yearlevel: "2"},
{name: "C", department_id: 9, yearlevel: "2"},
{name: "D", department_id: 9, yearlevel: "2"},
{name: "A", department_id: 10, yearlevel: "2"},
{name: "B", department_id: 10, yearlevel: "2"},
{name: "C", department_id: 10, yearlevel: "2"},
{name: "D", department_id: 10, yearlevel: "2"},
{name: "A", department_id: 1, yearlevel: "3"},
{name: "B", department_id: 1, yearlevel: "3"},
{name: "C", department_id: 1, yearlevel: "3"},
{name: "D", department_id: 1, yearlevel: "3"},
{name: "A", department_id: 2, yearlevel: "3"},
{name: "B", department_id: 2, yearlevel: "3"},
{name: "C", department_id: 2, yearlevel: "3"},
{name: "D", department_id: 2, yearlevel: "3"},
{name: "A", department_id: 3, yearlevel: "3"},
{name: "B", department_id: 3, yearlevel: "3"},
{name: "C", department_id: 3, yearlevel: "3"},
{name: "D", department_id: 3, yearlevel: "3"},
{name: "A", department_id: 4, yearlevel: "3"},
{name: "B", department_id: 4, yearlevel: "3"},
{name: "C", department_id: 4, yearlevel: "3"},
{name: "D", department_id: 4, yearlevel: "3"},
{name: "A", department_id: 5, yearlevel: "3"},
{name: "B", department_id: 5, yearlevel: "3"},
{name: "C", department_id: 5, yearlevel: "3"},
{name: "D", department_id: 5, yearlevel: "3"},
{name: "A", department_id: 6, yearlevel: "3"},
{name: "B", department_id: 6, yearlevel: "3"},
{name: "C", department_id: 6, yearlevel: "3"},
{name: "D", department_id: 6, yearlevel: "3"},
{name: "A", department_id: 7, yearlevel: "3"},
{name: "B", department_id: 7, yearlevel: "3"},
{name: "C", department_id: 7, yearlevel: "3"},
{name: "D", department_id: 7, yearlevel: "3"},
{name: "A", department_id: 8, yearlevel: "3"},
{name: "B", department_id: 8, yearlevel: "3"},
{name: "C", department_id: 8, yearlevel: "3"},
{name: "D", department_id: 8, yearlevel: "3"},
{name: "A", department_id: 9, yearlevel: "3"},
{name: "B", department_id: 9, yearlevel: "3"},
{name: "C", department_id: 9, yearlevel: "3"},
{name: "D", department_id: 9, yearlevel: "3"},
{name: "A", department_id: 10, yearlevel: "3"},
{name: "B", department_id: 10, yearlevel: "3"},
{name: "C", department_id: 10, yearlevel: "3"},
{name: "D", department_id: 10, yearlevel: "3"},
{name: "A", department_id: 1, yearlevel: "4"},
{name: "B", department_id: 1, yearlevel: "4"},
{name: "C", department_id: 1, yearlevel: "4"},
{name: "D", department_id: 1, yearlevel: "4"},
{name: "A", department_id: 2, yearlevel: "4"},
{name: "B", department_id: 2, yearlevel: "4"},
{name: "C", department_id: 2, yearlevel: "4"},
{name: "D", department_id: 2, yearlevel: "4"},
{name: "A", department_id: 3, yearlevel: "4"},
{name: "B", department_id: 3, yearlevel: "4"},
{name: "C", department_id: 3, yearlevel: "4"},
{name: "D", department_id: 3, yearlevel: "4"},
{name: "A", department_id: 4, yearlevel: "4"},
{name: "B", department_id: 4, yearlevel: "4"},
{name: "C", department_id: 4, yearlevel: "4"},
{name: "D", department_id: 4, yearlevel: "4"},
{name: "A", department_id: 5, yearlevel: "4"},
{name: "B", department_id: 5, yearlevel: "4"},
{name: "C", department_id: 5, yearlevel: "4"},
{name: "D", department_id: 5, yearlevel: "4"},
{name: "A", department_id: 6, yearlevel: "4"},
{name: "B", department_id: 6, yearlevel: "4"},
{name: "C", department_id: 6, yearlevel: "4"},
{name: "D", department_id: 6, yearlevel: "4"},
{name: "A", department_id: 7, yearlevel: "4"},
{name: "B", department_id: 7, yearlevel: "4"},
{name: "C", department_id: 7, yearlevel: "4"},
{name: "D", department_id: 7, yearlevel: "4"},
{name: "A", department_id: 8, yearlevel: "4"},
{name: "B", department_id: 8, yearlevel: "4"},
{name: "C", department_id: 8, yearlevel: "4"},
{name: "D", department_id: 8, yearlevel: "4"},
{name: "A", department_id: 9, yearlevel: "4"},
{name: "B", department_id: 9, yearlevel: "4"},
{name: "C", department_id: 9, yearlevel: "4"},
{name: "D", department_id: 9, yearlevel: "4"},
{name: "A", department_id: 10, yearlevel: "4"},
{name: "B", department_id: 10, yearlevel: "4"},
{name: "C", department_id: 10, yearlevel: "4"},
{name: "D", department_id: 10, yearlevel: "4"}

	])

day_timeslots = DayTimeslot.create ([
{day_id: 1, timeslot_id: 1},
{day_id: 1, timeslot_id: 2},
{day_id: 1, timeslot_id: 3},
{day_id: 1, timeslot_id: 4},
{day_id: 1, timeslot_id: 5},
{day_id: 1, timeslot_id: 6},
{day_id: 1, timeslot_id: 7},
{day_id: 1, timeslot_id: 8},
{day_id: 1, timeslot_id: 9},
{day_id: 1, timeslot_id: 10},
{day_id: 1, timeslot_id: 11},
{day_id: 1, timeslot_id: 12},
{day_id: 1, timeslot_id: 13},
{day_id: 1, timeslot_id: 14},
{day_id: 1, timeslot_id: 15},
{day_id: 1, timeslot_id: 16},
{day_id: 1, timeslot_id: 17},
{day_id: 1, timeslot_id: 18},
{day_id: 1, timeslot_id: 19},
{day_id: 1, timeslot_id: 20},
{day_id: 1, timeslot_id: 21},
{day_id: 1, timeslot_id: 22},
{day_id: 1, timeslot_id: 23},
{day_id: 1, timeslot_id: 24},
{day_id: 1, timeslot_id: 25},
{day_id: 1, timeslot_id: 26},
{day_id: 1, timeslot_id: 27},
{day_id: 2, timeslot_id: 1},
{day_id: 2, timeslot_id: 2},
{day_id: 2, timeslot_id: 3},
{day_id: 2, timeslot_id: 4},
{day_id: 2, timeslot_id: 5},
{day_id: 2, timeslot_id: 6},
{day_id: 2, timeslot_id: 7},
{day_id: 2, timeslot_id: 8},
{day_id: 2, timeslot_id: 9},
{day_id: 2, timeslot_id: 10},
{day_id: 2, timeslot_id: 11},
{day_id: 2, timeslot_id: 12},
{day_id: 2, timeslot_id: 13},
{day_id: 2, timeslot_id: 14},
{day_id: 2, timeslot_id: 15},
{day_id: 2, timeslot_id: 16},
{day_id: 2, timeslot_id: 17},
{day_id: 2, timeslot_id: 18},
{day_id: 2, timeslot_id: 19},
{day_id: 2, timeslot_id: 20},
{day_id: 2, timeslot_id: 21},
{day_id: 2, timeslot_id: 22},
{day_id: 2, timeslot_id: 23},
{day_id: 2, timeslot_id: 24},
{day_id: 2, timeslot_id: 25},
{day_id: 2, timeslot_id: 26},
{day_id: 2, timeslot_id: 27},
{day_id: 3, timeslot_id: 1},
{day_id: 3, timeslot_id: 2},
{day_id: 3, timeslot_id: 3},
{day_id: 3, timeslot_id: 4},
{day_id: 3, timeslot_id: 5},
{day_id: 3, timeslot_id: 6},
{day_id: 3, timeslot_id: 7},
{day_id: 3, timeslot_id: 8},
{day_id: 3, timeslot_id: 9},
{day_id: 3, timeslot_id: 10},
{day_id: 3, timeslot_id: 11},
{day_id: 3, timeslot_id: 12},
{day_id: 3, timeslot_id: 13},
{day_id: 3, timeslot_id: 14},
{day_id: 3, timeslot_id: 15},
{day_id: 3, timeslot_id: 16},
{day_id: 3, timeslot_id: 17},
{day_id: 3, timeslot_id: 18},
{day_id: 3, timeslot_id: 19},
{day_id: 3, timeslot_id: 20},
{day_id: 3, timeslot_id: 21},
{day_id: 3, timeslot_id: 22},
{day_id: 3, timeslot_id: 23},
{day_id: 3, timeslot_id: 24},
{day_id: 3, timeslot_id: 25},
{day_id: 3, timeslot_id: 26},
{day_id: 3, timeslot_id: 27},
{day_id: 4, timeslot_id: 1},
{day_id: 4, timeslot_id: 2},
{day_id: 4, timeslot_id: 3},
{day_id: 4, timeslot_id: 4},
{day_id: 4, timeslot_id: 5},
{day_id: 4, timeslot_id: 6},
{day_id: 4, timeslot_id: 7},
{day_id: 4, timeslot_id: 8},
{day_id: 4, timeslot_id: 9},
{day_id: 4, timeslot_id: 10},
{day_id: 4, timeslot_id: 11},
{day_id: 4, timeslot_id: 12},
{day_id: 4, timeslot_id: 13},
{day_id: 4, timeslot_id: 14},
{day_id: 4, timeslot_id: 15},
{day_id: 4, timeslot_id: 16},
{day_id: 4, timeslot_id: 17},
{day_id: 4, timeslot_id: 18},
{day_id: 4, timeslot_id: 19},
{day_id: 4, timeslot_id: 20},
{day_id: 4, timeslot_id: 21},
{day_id: 4, timeslot_id: 22},
{day_id: 4, timeslot_id: 23},
{day_id: 4, timeslot_id: 24},
{day_id: 4, timeslot_id: 25},
{day_id: 4, timeslot_id: 26},
{day_id: 4, timeslot_id: 27}
	])

 users = User.create([{name: "zendex", password: "123"}])

professors = Professor.create([
{lastname: "ACERO", firstname: "Liwayway", middleinitial: "H", status: "FT" },
{lastname:"ACHACOSO",firstname:"Marc David",middleinitial:"C", status: "FT 3rd Pro" },
{lastname:"AGREDA",firstname:"Sybil",middleinitial:"L", status: "FT" },
{lastname:"ALAJAR",firstname:"Joffre",middleinitial:"M", status: "FT Admin" },
{lastname:"ALER",firstname:"Diosdado III",middleinitial:"M", status: "FT Admin" },
{lastname:"AMBION",firstname:"Larry",middleinitial:"J", status: "FT" },
{lastname:"ANGELES",firstname:"Moses Aaron",middleinitial:"T", status: "FT" },
{lastname:"ARANTE",firstname:"Jonathan", status: "FT 2nd Pro" } ,
{lastname:"BALBOA-CAHIG",firstname:"Jennifer",middleinitial:"A", status: "FT 2nd Pro Admin" },
{lastname:"BATINO",firstname:"Lamberto Jr.",middleinitial:"A", status: "FT Admin" },
{lastname:"BENGCO",firstname:"Ma. Jocelyn",middleinitial:"O", status: "FT Admin" },
{lastname:"BERNARDO",firstname:"Delilah",middleinitial:"G", status: "FT" },
{lastname:"BRANZUELA",firstname:"Tita",middleinitial:"E", status: "FT Admin" },
{lastname:"BRONOSA",firstname:"Charles",middleinitial:"D", status: "FT 2nd Pro" },
{lastname:"BUNAG",firstname:"Ronald", status: "FT 2nd Pro" },
{lastname:"BUSTAMANTE",firstname:"Christian Bryan",middleinitial:"S", status: "FT Admin" },
{lastname:"BUTAC",firstname:"Susan",middleinitial:"R", status: "FT" },
{lastname:"CABAYSA",firstname:"Carissa",middleinitial:"C", status: "FT" },
{lastname:"CAMACHO",firstname:"Matt",middleinitial:"D", status: "FT 2nd Pro" },
{lastname:"CARANGUIAN",firstname:"Rey",middleinitial:"M", status: "FT" },
{lastname:"CASTILLO",firstname:"Julio", status: "FT 1st Pro" },
{lastname:"CASTRO",firstname:"Raquel", status: "FT" },
{lastname:"CLEMENTE",firstname:"Paulo",middleinitial:"B", status: "FT" },
{lastname:"CRUZ",firstname:"Maria Eliza",middleinitial:"P", status: "FT 2nd Pro" },
{lastname:"CUARESMA",firstname:"Esther",middleinitial:"R", status: "FT" },
{lastname:"CUCIO",firstname:"Rita",middleinitial:"R", status: "FT 3rd Pro" },
{lastname:"DALUPING",firstname:"Rebecca",middleinitial:"C", status: "FT" },
{lastname:"DANGO",firstname:"Josephine",middleinitial:"C", status: "FT" },
{lastname:"DEJESUS",firstname:"Socorro",middleinitial:"D", status: "FT" },
{lastname:"DEROXAS",firstname:"Joseph", status: "FT 2nd Pro" },
{lastname:"DIAZ",firstname:"Dixie", status: "FT 2nd Pro" },
{lastname:"DIMARUCOT",firstname:"Heildenberg", status: "FT  2nd Pro" },
{lastname:"DONOZO",firstname:"Arnold", status: "FT 1st Pro" },
{lastname:"DULAY",firstname:"Teresita",middleinitial:"B", status: "FT" },
{lastname:"ESGUERRA",firstname:"Anna Maria",middleinitial:"C", status: "FT" },
{lastname:"ESTAFIA",firstname:"Luisita",middleinitial:"P", status: "FT" }, 
{lastname:"ESTRELLA",firstname:"Maria Lani",middleinitial:"S", status: "FT 2nd Pro" },
{lastname:"FEBRE",firstname:"Francisco Jr.",middleinitial:"A", status: "FT Admin" },
{lastname:"FERNANDO",firstname:"Araceli",middleinitial:"T", status: "FT Admin" },
{lastname:"FONSECA",firstname:"Jennifer", status: "FT" },
{lastname:"FONSECA",firstname:"Jesster",middleinitial:"B", status: "FT" },
{lastname:"GABRIEL",firstname:"Nancy",middleinitial:"K", status: "FT Admin" },
{lastname:"GALANG",firstname:"Gary",middleinitial:"M", status: "FT 3rd Pro" },
{lastname:"GEMENTIZA",firstname:"Rivero", status: "FT 1st Pro" },
{lastname:"GUETA",firstname:"Maria FeRebecca",middleinitial:"D", status: "FT" },
{lastname:"GUIA",firstname:"Kim", status: "FT 2nd Pro" },
{lastname:"IRINCO-SALINAS",firstname:"Reiza",middleinitial:"R", status: "FT" },
{lastname:"JIMENEZ",firstname:"Ma.Luz",middleinitial:"LM", status: "FT" },
{lastname:"JOCSON",firstname:"Magdalena",middleinitial:"O", status: "FT" },
{lastname:"LEAL",firstname:"Melanio",middleinitial:"L", status: "FT Admin" },
{lastname:"LUGTU",firstname:"Vincent",middleinitial:"E", status: "FT 3rd Pro" },
{lastname:"LUNA",firstname:"Alden Reuben", status: "FT 3rd Pro" },
{lastname:"MACAPAGAL",firstname:"Luisito", status: "FT" },
{lastname:"MANAHAN",firstname:"Antonino Arturo",middleinitial:"C", status: "FT" },
{lastname:"MANGUBAT",firstname:"Dennis",middleinitial:"DP", status: "FT 2nd Pro" },
{lastname:"MARCELINO",firstname:"Ramon Benedicto",middleinitial:"N", status: "FT" },
{lastname:"MARTINEZ",firstname:"Kerwin Mark",middleinitial:"D", status: "FT" },
{lastname:"MATITU",firstname:"Bayani",middleinitial:"C", status: "FT" },
{lastname:"MORENO",firstname:"Jackqui",middleinitial:"R", status: "FT Admin" },
{lastname:"MUÑEZ",firstname:"Jephte",middleinitial:"O", status: "FT 1st Pro" },
{lastname:"NATIVIDAD",firstname:"Lizel Rose",middleinitial:"Q", status: "FT  2nd Pro" },
{lastname:"NIEVA",firstname:"Alvin",middleinitial:"M", status: "FT Admin" },
{lastname:"OASAN",firstname:"Albert",middleinitial:"C", status: "FT" },
{lastname:"PACULANAN",firstname:"Ronel",middleinitial:"S", status: "FT" },
{lastname:"PALABRICA",firstname:"Jose Maria",middleinitial:"J", status: "FT 2nd Pro" },
{lastname:"PASQUIN",firstname:"Eric",middleinitial:"G", status: "FT Admin" },
{lastname:"PEREZ",firstname:"Renelyn",middleinitial:"G", status: "FT 2nd Pro" },
{lastname:"PISCOS",firstname:"James Loreto",middleinitial:"C", status: "FT Admin" },
{lastname:"PLENO",firstname:"Noel Francisco", status: "FT 3rd Pro" },
{lastname:"PRUDENTE",firstname:"Josephine",middleinitial:"E", status: "FT" },
{lastname:"QUILON",firstname:"Annabel",middleinitial:"D", status: "FT" },
{lastname:"RADA",firstname:"Ester",middleinitial:"T", status: "FT" },
{lastname:"RAMIREZ",firstname:"Neilia",middleinitial:"B", status: "FT" },
{lastname:"RAMOS",firstname:"Jennifer",middleinitial:"T", status: "FT Admin" },
{lastname:"RAMOS",firstname:"Pilipino",middleinitial:"A", status: "FT" },
{lastname:"REMIGIO",firstname:"Candida",middleinitial:"P", status: "FT" },
{lastname:"REVILLA",firstname:"Nerissa",middleinitial:"M", status: "FT Admin" },
{lastname:"REYES",firstname:"Marvin",middleinitial:"R", status: "FT Admin" },
{lastname:"REYES",firstname:"Violeta",middleinitial:"C", status: "FT" },
{lastname:"RIVERO",firstname:"Rowena",middleinitial:"J", status: "FT" },
{lastname:"ROMERO",firstname:"Alejandro Jr.",middleinitial:"T", status: "FT" },
{lastname:"ROQUE",firstname:"Ma. Simplicia", status: "FT 2nd Pro" },
{lastname:"RUBIO",firstname:"Michael JohnY", status: "FT Admin" },
{lastname:"RUZOL",firstname:"Hipolito",middleinitial:"S", status: "FT" },
{lastname:"SAMPAGA",firstname:"Genesis",middleinitial:"L", status: "FT 3rd Pro" },
{lastname:"SANCHEZ",firstname:"Frederick", status: "FT 2nd Pro" },
{lastname:"SANTANA",firstname:"Don",middleinitial:"A", status: "FT" },
{lastname:"SANTANDER",firstname:"Noel",middleinitial:"D", status: "FT" },
{lastname:"SANTIAGO",firstname:"Rosalinda",middleinitial:"B", status: "FT 3rd Pro" },
{lastname:"SANTOS",firstname:"Gerard Mark",middleinitial:"C", status: "FT 2nd  Pro" },
{lastname:"SANTOS",firstname:"Matilde",middleinitial:"M", status: "FT" },
{lastname:"SERRANO",firstname:"Minerva",middleinitial:"T", status: "FT" },
{lastname:"TABLANG",firstname:"Joselito",middleinitial:"A", status: "FT Admin" },
{lastname:"TENDERO",firstname:"Ma. Pamela",middleinitial:"G", status: "FT  2nd Pro Admin" },
{lastname:"TIBI",firstname:"Elsa",middleinitial:"R", status: "FT 2nd Pro" },
{lastname:"TIU",firstname:"Catalina",middleinitial:"P", status: "FT" },
{lastname:"TUTOR",firstname:"Julius",middleinitial:"B", status: "FT 2nd Pro" },
{lastname:"TUY",firstname:"Fedeliz",middleinitial:"S", status: "FT Admin" },
{lastname:"URETA",firstname:"Lorisma", status: "FT" },
{lastname:"VILORIA",firstname:"Rulina",middleinitial:"B", status: "FT Admin" },
{lastname:"VIRAY",firstname:"EdilbertoJr.",middleinitial:"B", status: "FT" },
{lastname:"VIRGINO",firstname:"Josephine",middleinitial:"S", status: "FT 3rd Pro" },
{lastname:"YU",firstname:"Dolores",middleinitial:"N", status: "FT" }

	])



timeslots = Timeslot.create([
{start: '07:30', finish: '08:30'},
{start: '07:30', finish: '09:00'},
{start: '07:30', finish: '09:30'},
{start: '07:30', finish: '10:30'},

{start: '08:00', finish: '09:00'},
{start: '08:00', finish: '09:30'},
{start: '08:00', finish: '10:00'},
{start: '08:00', finish: '11:00'},

{start: '08:30', finish: '09:30'},
{start: '08:30', finish: '10:00'},
{start: '08:30', finish: '10:30'},
{start: '08:30', finish: '11:30'},

{start: '09:00', finish: '10:00'},
{start: '09:00', finish: '10:30'},
{start: '09:00', finish: '11:00'},
{start: '09:00', finish: '12:00'},

{start: '09:30', finish: '10:30'},
{start: '09:30', finish: '11:00'},
{start: '09:30', finish: '11:30'},
{start: '09:30', finish: '12:30'},

{start: '10:00', finish: '11:00'},
{start: '10:00', finish: '11:30'},
{start: '10:00', finish: '12:00'},
{start: '10:00', finish: '13:00'},

{start: '10:30', finish: '11:30'},
{start: '10:30', finish: '12:00'},
{start: '10:30', finish: '12:30'},
{start: '10:30', finish: '13:30'},

{start: '11:00', finish: '12:00'},
{start: '11:00', finish: '12:30'},
{start: '11:00', finish: '13:00'},
{start: '11:00', finish: '14:00'},

{start: '11:30', finish: '12:30'},
{start: '11:30', finish: '13:00'},
{start: '11:30', finish: '13:30'},
{start: '11:30', finish: '14:30'},

{start: '12:00', finish: '13:00'},
{start: '12:00', finish: '13:30'},
{start: '12:00', finish: '14:00'},
{start: '12:00', finish: '15:00'},

{start: '12:30', finish: '13:30'},
{start: '12:30', finish: '14:00'},
{start: '12:30', finish: '14:30'},
{start: '12:30', finish: '15:30'},

{start: '13:00', finish: '14:00'},
{start: '13:00', finish: '14:30'},
{start: '13:00', finish: '15:00'},
{start: '13:00', finish: '16:00'},

{start: '13:30', finish: '14:30'},
{start: '13:30', finish: '15:00'},
{start: '13:30', finish: '15:30'},
{start: '13:30', finish: '16:30'},

{start: '14:00', finish: '15:00'},
{start: '14:00', finish: '15:30'},
{start: '14:00', finish: '16:00'},
{start: '14:00', finish: '17:00'},

{start: '14:30', finish: '15:30'},
{start: '14:30', finish: '16:00'},
{start: '14:30', finish: '16:30'},
{start: '14:30', finish: '17:30'},

{start: '15:00', finish: '16:00'},
{start: '15:00', finish: '16:30'},
{start: '15:00', finish: '17:00'},
{start: '15:00', finish: '18:00'},

{start: '15:30', finish: '16:30'},
{start: '15:30', finish: '17:00'},
{start: '15:30', finish: '17:30'},
{start: '15:30', finish: '18:30'},

{start: '16:00', finish: '17:00'},
{start: '16:00', finish: '17:30'},
{start: '16:00', finish: '18:00'},
{start: '16:00', finish: '19:00'},

{start: '16:30', finish: '17:30'},
{start: '16:30', finish: '18:00'},
{start: '16:30', finish: '18:30'},
{start: '16:30', finish: '19:30'},

{start: '17:00', finish: '18:00'},
{start: '17:00', finish: '18:30'},
{start: '17:00', finish: '19:00'},
{start: '17:00', finish: '20:00'},

{start: '17:30', finish: '18:30'},
{start: '17:30', finish: '19:00'},
{start: '17:30', finish: '19:30'},
{start: '17:30', finish: '20:30'},

{start: '18:10', finish: '19:10'},
{start: '18:10', finish: '18:40'},
{start: '18:10', finish: '20:10'},
{start: '18:10', finish: '21:10'},

{start: '18:40', finish: '19:40'},
{start: '18:40', finish: '20:10'},
{start: '18:40', finish: '20:40'},

{start: '19:10', finish: '20:10'},
{start: '19:10', finish: '20:40'},
{start: '19:10', finish: '21:10'},

{start: '19:40', finish: '20:40'},
{start: '19:40', finish: '21:10'},

{start: '20:10', finish: '21:10'},



	])

days = Day.create([
{ name: "MF", desc: "Monday/Friday" },
{ name: "TTh", desc: "Tuesday/Thursday" },
{ name: "W", desc: "Wednesday" },
{ name: "S", desc: "Saturday" },
	])

rooms = Room.create([
{
name: "Lab A" }, {
name: "Lab B" }, {
name: "Lab C" }, {
name: "Lab D" }, {
name: "12b" }, {
name: "12c" }, {
name: "12E" }, {
name: "12F" }, {
name: "12G" }, {
name: "12I" }, {
name: "12J" }, {
name: "12K" }, {
name: "12L" }, {
name: "12M" }, {
name: "12Q" }, {
name: "12R" }, {
name: "12S" }, {
name: "12V" }, {
name: "12W" }, {
name: "12X" }, {
name: "12Y" }, {
name: "13B" }, {
name: "13C" }, {
name: "13D" }, {
name: "13E" }, {
name: "13F" }, {
name: "13G" }, {
name: "13H" }, {
name: "13I" }, {
name: "13J" }, {
name: "13K" }, {
name: "13L" }, {
name: "13M" }, {
name: "13O" }, {
name: "13Q" }, {
name: "13R" }, {
name: "13S" }, {
name: "13T" }, {
name: "13W" }, {
name: "13X" }, {
name: "13Y" }, {
name: "33C" }, {
name: "33D" }, {
name: "33E" }, {
name: "33F" }, {
name: "33G" }, {
name: "33H" }, {
name: "33I" }, {
name: "33J" }, {
name: "33K" }, {
name: "33L" }, {
name: "34C" }, {
name: "34D" }, {
name: "34E" }, {
name: "34F" }, {
name: "34G" }, {
name: "34H" }, {
name: "34I" }, {
name: "34J" }, {
name: "34K" }, {
name: "34L" }, {
name: "34M" }, {
name: "34N" }, {
name: "34O" }, {
name: "34P" }, {
name: "41B" }, {
name: "41C" }, {
name: "41D" }, {
name: "41E" }, {
name: "41F" }, {
name: "41G" }, {
name: "41H" }, {
name: "41I" }, {
name: "52A" }, {
name: "53B" }, {
name: "54B" }, {
name: "54C" }, {
name: "52C" }

])

subjects = Subject.create([
{name:"ACC01"	, desc:"Fundamentals of Accounting", load:3},
{name:"ACC02"	, desc:"Partnership and Corporation Accounting", load:3},
{name:"ACC03"	, desc:"Financial Accounting, Part 1", load:3},
{name:"ACC04"	, desc:"Financial Accounting, Part I", load:3},
{name:"ACC05"	, desc:"Theory of Accounts-Financial Accounting and Reporting", load:3},
{name:"ACC06"	, desc:"Advance Accounting Problems, Part I", load:3},
{name:"ACC07"	, desc:"Advance Accounting Problems, Part II", load:3},
{name:"ACC08"	, desc:"Financial Management, Part I", load:3},
{name:"ACC09"	, desc:"Financial Management, Part II", load:3},
{name:"ACC10"	, desc:"Cost Accounting and Cost Management", load:3},
{name:"ACC11"	, desc:"Accounting Office Practicum", load:3},
{name:"ACC12"	, desc:"Auditing and Assurance Service, Part I", load:3},
{name:"ACC13"	, desc:"Auditing Assurance Service Part II", load:3},
{name:"ACC14"	, desc:"Management Accounting, Part I", load:3},
{name:"ACC15"	, desc:"Management Accounting Part II", load:3},
{name:"ACC16"	, desc:"Management Consultancy", load:3},
{name:"ACC17"	, desc:"Accounting Review Workshop I (with Accounting for Governmental, Not-For-Profit Entitles & Specialize Industries)", load:3},
{name:"ACC18"	, desc:"Accounting Information System", load:3},
{name:"ACC18"	, desc:"Fundamentals of Accounting Part II", load:3},
{name:"ACC19"	, desc:"Auditing in a CIS Environment", load:3},
{name:"ACC1A"	, desc:"Fundamentals of Accounting, Part 1", load:3},
{name:"ACC1B"	, desc:"Fundamentals of Accounting, Part 2", load:3},
{name:"ACC1E"	, desc:"Fundamentals of Accounting", load:3},
{name:"ACC2A"	, desc:"Partnership and Corporation Accounting", load:3},
{name:"ACC2E"	, desc:"Financial Accounting", load:3},
{name:"ACC4A"	, desc:"Management Accounting", load:3},
{name:"ACC4C"	, desc:"Management Accounting", load:3},
{name:"ACCF"	, desc:"Financial Accounting for Financial Management Majors", load:3},
{name:"ACCF2"	, desc:"Managerial Accounting for Financial Management majors", load:3},
{name:"ADSTT"	, desc:"Advance Statistics", load:3},
{name:"ARTAP"	, desc:"Art Appreciation", load:3},
{name:"ASCIV"	, desc:"Asian Civilization", load:3},
{name:"ASTAT"	, desc:"Applied Business Statistics", load:3},
{name:"BENE1"	, desc:"St. Benedict and the Holy Rule", load:3},
{name:"BENE2"	, desc:"Selected Topics on the Rule of St. Benedict", load:3},
{name:"BENE3"	, desc:"Benedictine Spirituality and the Corporate World", load:3},
{name:"BFM01"	, desc:"Financial Management", load:3},
{name:"BFM02"	, desc:"Financial Analysis and Reporting", load:3},
{name:"BFM03"	, desc:"Banking and Financial Institution", load:3},
{name:"BFM04"	, desc:"Monetary Policy and Central Banking", load:3},
{name:"BFM05"	, desc:"Investment and Portfolio Management", load:3},
{name:"BFM06"	, desc:"Credit and Collection", load:3},
{name:"BFM07"	, desc:"Capital Markets", load:3},
{name:"BFM08"	, desc:"Strategic Financial Management", load:3},
{name:"BFM09"	, desc:"Special Topics in Financial Management", load:3},
{name:"BIOSC"	, desc:"Biological Science", load:3},
{name:"BLW01"	, desc:"Obligations and Contracts", load:3},
{name:"BLW02"	, desc:"Negotiable Instruments and Other Special Laws", load:3},
{name:"BLW03"	, desc:"Law on Business Organizations", load:3},
{name:"BLW04"	, desc:"Law on Sales, Agencies, Bailment and Credit Transactions", load:3},
{name:"CHEM1"	, desc:"General Chemistry with Laboratory", load:3},
{name:"CHEM2"	, desc:"Organic Chemistry with Laboratory", load:3},
{name:"COMP1"	, desc:"Fundamentals of Computer Software and Application", load:3},
{name:"COMP2"	, desc:"Fundamentals of Programming and Database Theory and Applications", load:3},
{name:"COMP3"	, desc:"Web Page Design and Animation", load:3},
{name:"COMP3A"	, desc:"IT Concepts and System Analysis and Design Development", load:3},
{name:"ECO01"	, desc:"Fundamentals of Economics", load:3},
{name:"ECO02"	, desc:"Macroeconomic Theory", load:3},
{name:"ECO03"	, desc:"Intermediate Microeconomic Theory ", load:3},
{name:"ECO04"	, desc:"Intermediate Macroeconomic Theory", load:3},
{name:"ECO05"	, desc:"Mathematical Economics", load:3},
{name:"ECO06"	, desc:"Econometrics I", load:3},
{name:"ECO07"	, desc:"Econometrics II", load:3},
{name:"ECO08"	, desc:"Development and Policy Economics", load:3},
{name:"ECO09"	, desc:"Monetary Theory and Policy", load:3},
{name:"ECO10"	, desc:"Management Economics", load:3},
{name:"ECO11"	, desc:"Economics of Policy Formulations Analysis andImplementation", load:3},
{name:"ECO12"	, desc:"Development of Economic Ideas", load:3},
{name:"ECO13"	, desc:"Human Resource Economics", load:3},
{name:"ECO14"	, desc:"Investment and Financial Markets", load:3},
{name:"ECO15"	, desc:"Public Economics Expenditures", load:3},
{name:"ECO16"	, desc:"Public Economics Taxation", load:3},
{name:"ECO17"	, desc:"Computer and Data Resource for Economics", load:3},
{name:"ECO18"	, desc:"Economics of Natural Resource and Sustainability", load:3},
{name:"ECO19"	, desc:"Regional and Urban Economics", load:3},
{name:"ECO20"	, desc:"Economic of Law", load:3},
{name:"ECO21"	, desc:"Industrial Organization Theory and Policy", load:3},
{name:"ECO22"	, desc:"International Economics", load:3},
{name:"ECO23"	, desc:"Agro- Industrial Policy Analysis with Project Planning and Evaluation", load:3},
{name:"ECO24"	, desc:"ElectiveHealth EconomicsEconomics of EducationTransportation Economics", load:3},
{name:"ECO25"	, desc:"Economic Research I", load:3},
{name:"ECO26"	, desc:"Economic Research II", load:3},
{name:"ECO27"	, desc:"Economic Internship", load:3},
{name:"ECO2B"	, desc:"Fiscal Studies", load:3},
{name:"ENG01"	, desc:"Basic English Language Competency", load:3},
{name:"ENG02"	, desc:"Business Communication", load:3},
{name:"ENG03"	, desc:"Speech Communications", load:3},
{name:"ENG04"	, desc:"Research Methods and Applications", load:3},
{name:"ENG06"	, desc:"Argumentation and Debate", load:3},
{name:"ENG08"	, desc:"Expository Writing", load:3},
{name:"ENG4A"	, desc:"Technical Writing in Marketing Research", load:3},
{name:"ENG4B"	, desc:"Technical Writing for Business", load:3},
{name:"ENGO2"	, desc:"Business Communication", load:3},
{name:"ENT01"	, desc:"Entrepreneurial Behavior", load:3},
{name:"ENT02"	, desc:"Business Opportunities", load:3},
{name:"ENT03"	, desc:"Business Opportunities 2", load:3},
{name:"ENT04"	, desc:"Cost Accounting", load:3},
{name:"ENT05"	, desc:"Business Plan 1", load:3},
{name:"ENT06"	, desc:"Business Plan 2", load:3},
{name:"ENT07"	, desc:"Management Accounting", load:3},
{name:"ENT08"	, desc:"Operations Research", load:3},
{name:"ENT09"	, desc:"Business Plan Implementation 1", load:3},
{name:"ENT10"	, desc:"Business Plan Implementation 2", load:3},
{name:"ENT11"	, desc:"Entrepreneurship Fora and Assimilation", load:3},
{name:"ENT12"	, desc:"Strategic Management and Business Policy", load:3},
{name:"ENTEA"	, desc:"New Market Development", load:3},
{name:"ENTEB"	, desc:"Managing the Family Firm", load:3},
{name:"ENTEC"	, desc:"Agricultural Entrepreneurship", load:3},
{name:"ENTED"	, desc:"Managing a service Enterprise", load:3},
{name:"ENTEE"	, desc:"Managing a Manufacturing Enterprise", load:3},
{name:"ENTEF"	, desc:"Export Marketing", load:3},
{name:"ENTEG"	, desc:"Capital and Securities Market", load:3},
{name:"ENTEH"	, desc:"Venture Capital", load:3},
{name:"ENVSC"	, desc:"Earth Science and the Environment", load:3},
{name:"ERTSC"	, desc:"Earth Science and the Environment", load:3},
{name:"FILI1"	, desc:"Komunikasyon sa Akademikong Filipino", load:3},
{name:"FILI2"	, desc:"Pagbasa at Pagsulat Tungo sa Pananaliksik", load:3},
{name:"FILI3"	, desc:"Masining na Pagpapahayag", load:3},
{name:"FIN01"	, desc:"Basic Finance", load:3},
{name:"FME0"	, desc:"Financial Controllership", load:3},
{name:"FME01"	, desc:"Islamic Finance", load:3},
{name:"FME02"	, desc:"Risk Management", load:3},
{name:"FME03"	, desc:"Public Finance", load:3},
{name:"FME04"	, desc:"Security Analysis", load:3},
{name:"HIS01"	, desc:"Philippine History and Culture", load:3},
{name:"HIS02"	, desc:"Society and Culture with Family Planning", load:3},
{name:"HIS03"	, desc:"Rizal’s Life and Writings", load:3},
{name:"HKD01"	, desc:"Physical Fitness Test/ Gymnastics/ Aerobics", load:3},
{name:"HKD02"	, desc:"Rhythmic Activities, Lead Up Games", load:3},
{name:"HKD03"	, desc:"Individual/ Dual Sports", load:3},
{name:"HKD04"	, desc:"Team Sports", load:3},
{name:"HMR06"	, desc:"Labor Relations and Negotiations", load:3},
{name:"HRE01"	, desc:"Managerial Accounting", load:3},
{name:"HRE02"	, desc:"Marketing Management", load:3},
{name:"HRE03"	, desc:"Entrepreneurial Management", load:3},
{name:"HRE04"	, desc:"Environmental Management", load:3},
{name:"HRE05"	, desc:"Logistics Management", load:3},
{name:"HRE06"	, desc:"Global/ International Trade", load:3},
{name:"HRE07"	, desc:"Project Management", load:3},
{name:"HRE08"	, desc:"Conflict Management", load:3},
{name:"HRE09"	, desc:"Creative Thinking", load:3},
{name:"HRM01"	, desc:"Administrative and Office Management", load:3},
{name:"HRM02"	, desc:"Recruitment and Selection", load:3},
{name:"HRM03"	, desc:"Labor Law and Legislation", load:3},
{name:"HRM04"	, desc:"Training and Development", load:3},
{name:"HRM05"	, desc:"Compensation Administration", load:3},
{name:"HRM07"	, desc:"Organizational Development", load:3},
{name:"HRM08"	, desc:"Strategic Human Resource Management", load:3},
{name:"HRM09"	, desc:"Special Topics in Human Resource Management", load:3},
{name:"HRSOP"	, desc:"Human Relations and Social Orientation Program", load:3},
{name:"HUM01"	, desc:"Art, Man, and Society", load:3},
{name:"IBE01"	, desc:"Principles of Management", load:3},
{name:"IBE02"	, desc:"Human Behavior in Business Organizations", load:3},
{name:"IBE03M"	, desc:"Human Resource Development", load:3},
{name:"IBE05"	, desc:"Business Finance and the Philippine Financial System", load:3},
{name:"IBE1B"	, desc:"Strategic Management", load:3},
{name:"ICT01"	, desc:"Information and Communications Technology Concept", load:3},
{name:"ICT02"	, desc:"Program Logic Formulation with Programming Part 1", load:3},
{name:"ICT03"	, desc:"Digital Logic Circuits", load:3},
{name:"ICT04"	, desc:"Computer Programming Part 2", load:3},
{name:"ICT05"	, desc:"Data Structures and Algorithm Analysis", load:3},
{name:"ICT06"	, desc:"Database Management System 1", load:3},
{name:"ICT07"	, desc:"Operating Systems", load:3},
{name:"ICT08"	, desc:"Database Management", load:3},
{name:"ICT09"	, desc:"Computer Graphics and Multi-media Systems", load:3},
{name:"ICT10"	, desc:"Object- Oriented Programming", load:3},
{name:"ICT11"	, desc:"Web- based Programming", load:3},
{name:"ICT12"	, desc:"Data Communication Systems", load:3},
{name:"ICT13"	, desc:"Information Resource Management", load:3},
{name:"ICT14"	, desc:"Quality Processes", load:3},
{name:"ICT15"	, desc:"Computer System Organization", load:3},
{name:"ICT16"	, desc:"Network Installation and Administration", load:3},
{name:"ICT17"	, desc:"Code of Ethics for ICT Professionals", load:3},
{name:"ICT18"	, desc:"Basic Systems Analysis and Design", load:3},
{name:"ICT19"	, desc:"Advanced Web Page Programming", load:3},
{name:"ICT20"	, desc:"Current/ Future Trends in Information and Communications Technology", load:3},
{name:"ICT21"	, desc:"Wireless Application", load:3},
{name:"ICT22"	, desc:"Advanced Systems Analysis and Design", load:3},
{name:"ICT23"	, desc:"E-commerce Technology", load:3},
{name:"ICT24"	, desc:"Research Project Proposal", load:3},
{name:"ICT25"	, desc:"Management Information Systems", load:3},
{name:"ICT26"	, desc:"Research Project Defense", load:3},
{name:"ICT27"	, desc:"Practicum", load:3},
{name:"ICT2E"	, desc:"Database with Spreadsheet", load:3},
{name:"ICT2L"	, desc:"Computer Graphics and Presentation Software", load:3},
{name:"LANG1"	, desc:"Foreign Language", load:3},
{name:"LGM01"	, desc:"Law on Persons and Family Relations", load:3},
{name:"LGM02"	, desc:"Legal Writing and Research", load:3},
{name:"LGM03"	, desc:"Law on Obligations and Contracts", load:3},
{name:"LIT01"	, desc:"Philippine Literature", load:3},
{name:"LIT02"	, desc:"World Literature", load:3},
{name:"LMG04"	, desc:"Law on Sales, Bailments and Credit Transactions", load:3},
{name:"LMG05"	, desc:"Law on Negotiable Instruments", load:3},
{name:"LMG06"	, desc:"Constitutional Law", load:3},
{name:"LMG07"	, desc:"Criminal Law", load:3},
{name:"LMG08"	, desc:"Banking and Insurance Laws", load:3},
{name:"LMG09"	, desc:"Business Organizations I (Agency and Partnership)", load:3},
{name:"LMG10"	, desc:"Business Organizations II (Corporations)", load:3},
{name:"LMG11"	, desc:"Labor Laws", load:3},
{name:"LMG13"	, desc:"Other Commercial Laws", load:3},
{name:"LMG14"	, desc:"Other Civil Laws", load:3},
{name:"LMG15"	, desc:"Income Taxation", load:3},
{name:"LMG16"	, desc:"Business Taxation", load:3},
{name:"LMG17"	, desc:"Business Forms and Procedures", load:3},
{name:"LMG18"	, desc:"Business and Legal Ethics", load:3},
{name:"MGT01"	, desc:"Principles of Management", load:3},
{name:"MGT02"	, desc:"Human Behavior in Organization", load:3},
{name:"MGT03"	, desc:"Social Responsibility and Good Governance", load:3},
{name:"MGT04 "	, desc:"Multi Cultural Human Resource Management", load:3},
{name:"MGT05"	, desc:"Production and Operations Management", load:3},
{name:"MGT05"	, desc:"Production/ Operations Management", load:3},
{name:"MGT06"	, desc:"Total Quality Management", load:3},
{name:"MGT07"	, desc:"Ethics in the Business Organization", load:3},
{name:"MGT08"	, desc:"Leadership Development", load:3},
{name:"MGT1L"	, desc:"Compensation Management", load:3},
{name:"MGT2L"	, desc:"Business Planning", load:3},
{name:"MGTO9"	, desc:"Business Policy and Strategic Management", load:3},
{name:"MKC01"	, desc:"Principles of Marketing", load:3},
{name:"MKC02"	, desc:"Consumer Behavior/Consumer Research Application", load:3},
{name:"MKC03"	, desc:"Professional Selling & Sales Management", load:3},
{name:"MKC04"	, desc:"Marketing Research", load:3},
{name:"MKC05A"	, desc:"Principles of Advertising and Sales Promotion", load:3},
{name:"MKC06A"	, desc:"Internet Marketing", load:3},
{name:"MKC07A"	, desc:"Corporate Communication Public Relations", load:3},
{name:"MKC08A"	, desc:"Distribution Management", load:3},
{name:"MKC09A"	, desc:"Strategic Marketing Management", load:3},
{name:"MKC10A"	, desc:"Retail Management", load:3},
{name:"MKC11A"	, desc:"Service Marketing", load:3},
{name:"MKC12A"	, desc:"Marketing Management", load:3},
{name:"MKC13A"	, desc:"Special Topics in Marketing Communication", load:3},
{name:"MKC14A"	, desc:"Information Marketing", load:3},
{name:"MKC15A"	, desc:"Corporate Communication Direct Marketing", load:3},
{name:"MKC18"	, desc:"Marketing Management", load:3},
{name:"MTH01"	, desc:"College Algebra", load:3},
{name:"MTH02"	, desc:"Mathematics of Investment", load:3},
{name:"MTH03"	, desc:"Mathematical Analysis", load:3},
{name:"MTH04"	, desc:"Quantitative Techniques in Business", load:3},
{name:"MTH05"	, desc:"Calculus with Analytical Geometry", load:3},
{name:"MTH06"	, desc:"Calculus", load:3},
{name:"NSTP1"	, desc:"National Service Training Program I", load:3},
{name:"NSTP2"	, desc:"National Service Training Program II", load:3},
{name:"OPE01"	, desc:"Marketing Management", load:3},
{name:"OPE02"	, desc:"Managerial Accounting", load:3},
{name:"OPE03"	, desc:"Financial Management", load:3},
{name:"OPE07"	, desc:"Environmental Management", load:3},
{name:"OPE08"	, desc:"Global/ International Trade", load:3},
{name:"OPE09"	, desc:"Enterprise Resource Planning", load:3},
{name:"OPM01"	, desc:"Operations Management", load:3},
{name:"OPM02"	, desc:"Inventory Management and Control", load:3},
{name:"OPM03"	, desc:"Logistics Management", load:3},
{name:"OPM04"	, desc:"Cost Accounting", load:3},
{name:"OPM06"	, desc:"Facilities Management", load:3},
{name:"OPM07"	, desc:"Project Management", load:3},
{name:"OPM08"	, desc:"Strategic Operations Management", load:3},
{name:"OPM09"	, desc:"Special Topics in Operations Management", load:3},
{name:"PEPBA"	, desc:"Bedan Awareness and Personality Development Program", load:3},
{name:"PHIL01"	, desc:"Introduction to Philosophy with Logic & Critical Thingking", load:3},
{name:"PHL02"	, desc:"Philosophy of the Human Person", load:3},
{name:"PHYSC"	, desc:"Physics", load:3},
{name:"POLSC"	, desc:"Introduction to Political Science with Philippine Government and Constitution", load:3},
{name:"PRACT"	, desc:"Human Resource Development Management Internship", load:3},
{name:"PRACTFM"	, desc:"Financial Management Internship", load:3},
{name:"PRACTMK"	, desc:"Internship in Marketing & Corporate Communications", load:3},
{name:"PSY01A"	, desc:"development psychology", load:3},
{name:"PSY02A"	, desc:"psychology of personality", load:3},
{name:"PSY03A"	, desc:"Psychology of Learning", load:3},
{name:"PSY04A"	, desc:"Social Psychology", load:3},
{name:"PSY05A"	, desc:"Industrial/Organization Psychology", load:3},
{name:"PSY06A"	, desc:"Physiology Psychology", load:3},
{name:"PSY07A"	, desc:"Psychological Testing 1 with Laboratory", load:3},
{name:"PSY08A"	, desc:"Psychology Testing 2", load:3},
{name:"PSY09A"	, desc:"Methods of Research", load:3},
{name:"PSY10A"	, desc:"Techniques in Counseling", load:3},
{name:"PSY11A"	, desc:"Abnormal Psychology", load:3},
{name:"PSY12A"	, desc:"Exeperimental Psychology", load:3},
{name:"PSY13A"	, desc:"Group Process", load:3},
{name:"PSY14A"	, desc:"Thesis 1", load:3},
{name:"PSY15A"	, desc:"Principles and Services of Guidance", load:3},
{name:"PSY16A"	, desc:"Elective 1", load:3},
{name:"PSY17A"	, desc:"Thesis 2", load:3},
{name:"PSY18A"	, desc:"Practicum 1", load:3},
{name:"PSY19A"	, desc:"Healthy Psychology", load:3},
{name:"PSY20A"	, desc:"Elective 2", load:3},
{name:"PSY21A"	, desc:"Clinical Psychology", load:3},
{name:"PSY22A"	, desc:"Practicum 2 (150 hours)", load:3},
{name:"PSY23A"	, desc:"History of Psychology", load:3},
{name:"PSY24A"	, desc:"Seminar in Psychology (Current Issues and Ethical Practice)", load:3},
{name:"PSYCH"	, desc:"General Psychology", load:3},
{name:"PSYS1"	, desc:"Fundamental Statistics with Computer Applications", load:3},
{name:"PSYS2"	, desc:"Advance Statistics", load:3},
{name:"RIZAL"	, desc:"Rizal’s Life & Works", load:3},
{name:"SOCAN"	, desc:"Sociology and Anthropology in the PhilippineBusiness Environment", load:3},
{name:"TAX01"	, desc:"Income Taxation", load:3},
{name:"TAX02"	, desc:"Transfer, Business and Other Taxes", load:3},
{name:"THED1"	, desc:"Introduction to Theology and Biblical Studies", load:3},
{name:"THED2"	, desc:"New Testament Studies", load:3},
{name:"THED3"	, desc:"Church, Sacraments and Family Life", load:3},
{name:"THED4"	, desc:"Contemporary Moral Theology", load:3},
{name:"THED5"	, desc:"Social Justice", load:3},
{name:"TRIGO"	, desc:"Trigonometry", load:3},
{name:"ZOO01"	, desc:"Invertibrate Psychology", load:3}
])